import { existsSync } from "node:fs";
import { chromium } from "playwright-core";
const executablePath = ["C:/Users/Duy/AppData/Local/ms-playwright/chromium-1234/chrome-win64/chrome.exe"].find(existsSync);
const browser = await chromium.launch({ executablePath, headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
await page.goto("http://localhost:5173/strategy-engine", { waitUntil: "networkidle" });
await page.waitForTimeout(1200);
const add = page.getByRole("button", { name: "+ ADD STRATEGY" });
await add.nth(0).click(); await add.nth(1).click();
await page.waitForTimeout(400);
const policy = page.locator("select").filter({ has: page.locator('option[value="weighted-score"]') });
console.log("policy selects found:", await policy.count());
console.log("threshold visible before:", await page.locator('.field-inert').count());
await policy.first().selectOption("weighted-score");
await page.waitForTimeout(400);
console.log("weight fields:", await page.locator(".weight-field").count());
console.log("threshold input now:", await page.locator('.field-inert').count() === 0 ? "editable" : "still inert");
await page.locator(".weight-field input").first().fill("2");
await page.waitForTimeout(200);
console.log("weight value:", await page.locator(".weight-field input").first().inputValue());
await page.screenshot({ path: ".scratch/ui-rescue/shots/final-engine-weighted.png", fullPage: true });
await browser.close();
