import { existsSync } from "node:fs";
import { chromium } from "playwright-core";
const executablePath = ["C:/Users/Duy/AppData/Local/ms-playwright/chromium-1234/chrome-win64/chrome.exe"].find(existsSync);
const browser = await chromium.launch({ executablePath, headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
page.on("pageerror", (e) => console.log("PAGEERROR", e.message));
await page.goto("http://localhost:5173/strategy-engine", { waitUntil: "networkidle" });
await page.waitForTimeout(1200);
const save = page.getByRole("button", { name: /SAVE COMPOSITE/ });
console.log("save disabled with 0 components:", await save.isDisabled());
console.log("blocked hint:", await page.locator(".builder-save .hint").innerText());
const add = page.getByRole("button", { name: "+ ADD STRATEGY" });
await add.nth(0).click();
console.log("save disabled with 1 component:", await save.isDisabled());
await add.nth(2).click();
await page.locator('input[placeholder="e.g. Alpha Trend 2.0"]').fill("Trend + Volatility demo");
await page.locator('input[placeholder="Describe the strategy logic..."]').fill("Majority vote of a trend and a volatility signal.");
await page.waitForTimeout(300);
console.log("save disabled when ready:", await save.isDisabled());
// Change a parameter to prove the form is interactive.
const fast = page.locator(".component-card").first().locator('input[type=number]').first();
await fast.fill("12");
await page.waitForTimeout(200);
console.log("fast period now:", await fast.inputValue());
// Policy switch reveals the weight fields.
await page.locator(".form-section select").last().selectOption("weighted-score").catch(()=>{});
await page.waitForTimeout(300);
console.log("weight fields after policy switch:", await page.locator(".weight-field").count());
await page.locator("select").filter({ hasText: "Majority Vote" }).first().selectOption("majority-vote").catch(()=>{});
await page.waitForTimeout(300);
await save.click();
await page.waitForSelector(".banner-success", { timeout: 30000 });
await page.waitForTimeout(6000);
console.log("saved:", await page.locator(".banner-success").innerText());
console.log("combined action:", await page.locator(".combined-output").innerText());
console.log("errors:", await page.locator(".banner-error").count());
await page.screenshot({ path: ".scratch/ui-rescue/shots/final-engine.png", fullPage: true });
await browser.close();
