import { existsSync, mkdirSync } from "node:fs";
import { chromium } from "playwright-core";
const executablePath = ["C:/Users/Duy/AppData/Local/ms-playwright/chromium-1234/chrome-win64/chrome.exe"].find(existsSync);
const ORIGIN = process.env.UI_ORIGIN ?? "http://localhost:5173";
const OUT = ".scratch/ui-rescue/shots"; mkdirSync(OUT, { recursive: true });
const browser = await chromium.launch({ executablePath, headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on("pageerror", (e) => console.log("PAGEERROR", e.message));
const requests = [];
page.on("request", (r) => { if (r.method() === "POST" && r.url().includes("/api/")) requests.push([r.url(), r.postData()]); });
await page.goto(`${ORIGIN}/strategy-engine`, { waitUntil: "networkidle" });
await page.waitForTimeout(1200);
const addButtons = page.getByRole("button", { name: "+ ADD STRATEGY" });
await addButtons.nth(0).click();
await addButtons.nth(1).click();
await page.waitForTimeout(600);
// fill name
const nameInput = page.locator('input[placeholder="e.g. Alpha Trend 2.0"]');
await nameInput.fill("UI Rescue Probe");
await page.waitForTimeout(300);
console.log("SAVE disabled?", await page.getByRole("button", { name: /SAVE COMPOSITE/ }).isDisabled());
await page.screenshot({ path: `${OUT}/engine-2components.png`, fullPage: true });
await page.getByRole("button", { name: /SAVE COMPOSITE/ }).click();
await page.waitForTimeout(6000);
console.log("--- POSTs ---");
for (const [u, d] of requests) console.log(u, d);
console.log("--- TEXT tail ---");
console.log((await page.evaluate(() => document.body.innerText)).slice(-1400));
await browser.close();
