// Random search generator: the MVP's required search method.
//
// Given a declared search space and a seed, it produces a reproducible sequence
// of valid candidates. Reproducibility comes entirely from the seeded random
// source, so the same seed and search space yield the same sequence in any
// process. Duplicates are avoided: a candidate whose content hash was already
// emitted is skipped, and the sequence ends once the generator cannot find a
// new unique candidate within `maxConsecutiveDuplicates` attempts.

import { SeededRandom } from "../../../platform/seeded-random.js";
import { createCandidateStrategy } from "./candidate-strategy-factory.js";
import { StrategyRegistry } from "./strategy-registry.js";
import { CombinationPolicyRegistry } from "./combination-policy-registry.js";
import type { StrategyParameterValue, StrategyParameters, ParameterSchema } from "../domain/parameter-schema.js";
import type { StrategyDescriptor } from "../domain/strategy.js";
import type { CandidateStrategy, GeneratorProvenance } from "../domain/candidate-strategy.js";
import type {
  GenerateRequest,
  GeneratorDescriptor,
  ParameterRange,
  SearchSpace,
  StrategyGenerator,
  VersionedRef
} from "../domain/strategy-generator.js";
import type { ComponentStrategyReference } from "../domain/composite-strategy.js";

const DEFAULT_MAX_CONSECUTIVE_DUPLICATES = 100;

const CONFIGURATION_SCHEMA: ParameterSchema = {
  properties: {
    maxConsecutiveDuplicates: {
      type: "integer",
      label: "Max consecutive duplicates",
      description: "The sequence ends after this many consecutive already-seen candidates.",
      minimum: 1,
      default: DEFAULT_MAX_CONSECUTIVE_DUPLICATES
    }
  },
  required: []
};

function round4(value: number): number {
  return Math.round(value * 10_000) / 10_000;
}

export class RandomStrategyGenerator implements StrategyGenerator {
  readonly descriptor: GeneratorDescriptor = {
    id: "random-search",
    version: "1.0.0",
    name: "Random search",
    description: "Draws valid candidates uniformly at random from the declared search space.",
    configurationSchema: CONFIGURATION_SCHEMA
  };

  constructor(
    private readonly strategies: StrategyRegistry,
    private readonly policies: CombinationPolicyRegistry
  ) {}

  generate(request: GenerateRequest): Iterable<CandidateStrategy> {
    const space = request.searchSpace;
    this.assertSearchSpace(space);
    this.assertParameterRanges(space);
    const maxConsecutiveDuplicates = this.readMaxConsecutiveDuplicates(request.configuration);
    const random = new SeededRandom(request.seed);
    const provenance: GeneratorProvenance = {
      id: this.descriptor.id,
      version: this.descriptor.version,
      configuration: request.configuration,
      seed: request.seed
    };

    const self = this;
    function* sequence(): Generator<CandidateStrategy> {
      const seen = new Set<string>();
      let consecutiveDuplicates = 0;
      while (consecutiveDuplicates < maxConsecutiveDuplicates) {
        const candidate = self.generateOne(space, random, provenance);
        if (seen.has(candidate.contentHash)) {
          consecutiveDuplicates += 1;
          continue;
        }
        seen.add(candidate.contentHash);
        consecutiveDuplicates = 0;
        yield candidate;
      }
    }
    return sequence();
  }

  private generateOne(
    space: SearchSpace,
    random: SeededRandom,
    provenance: GeneratorProvenance
  ): CandidateStrategy {
    const size = random.pick(space.compositeSizes);
    const chosen = random.sample(space.strategies, size);
    const components = chosen.map((ref) => this.componentFor(ref, space, random));

    if (size === 1) {
      const only = components[0]!;
      return createCandidateStrategy({
        specification: { kind: "single", id: only.id, version: only.version, parameters: only.parameters },
        generator: provenance
      });
    }

    const policyRef = random.pick(space.policies);
    return createCandidateStrategy({
      specification: {
        kind: "composite",
        composite: {
          id: "generated-composite",
          version: "1.0.0",
          name: `Composite of ${chosen.map((ref) => ref.id).join(" + ")}`,
          description: "Generated by random-search.",
          components,
          policy: {
            id: policyRef.id,
            version: policyRef.version,
            configuration: this.policyConfiguration(size, random)
          }
        }
      },
      generator: provenance
    });
  }

  private componentFor(ref: VersionedRef, space: SearchSpace, random: SeededRandom): ComponentStrategyReference {
    const runnable = this.strategies.resolve(ref);
    const parameters = this.parametersFor(runnable.descriptor, space, random);
    // Prove criterion 1 at the source: every emitted candidate passes validation.
    runnable.validateParameters(parameters);
    return { id: ref.id, version: ref.version, parameters };
  }

  private parametersFor(descriptor: StrategyDescriptor, space: SearchSpace, random: SeededRandom): StrategyParameters {
    const overrides = space.parameterRanges?.[descriptor.id];
    const parameters: Record<string, StrategyParameterValue> = {};
    for (const [field, definition] of Object.entries(descriptor.parameterSchema.properties)) {
      if (definition.type === "boolean") {
        parameters[field] = random.nextFloat() < 0.5;
        continue;
      }
      if (definition.type === "enum") {
        parameters[field] = random.pick(definition.values);
        continue;
      }
      const range = this.numericRange(field, definition, overrides?.[field]);
      if (range === undefined) {
        // No usable range: fall back to the schema default, which is always valid.
        if (definition.default === undefined) {
          throw new Error(
            `GENERATOR_PARAMETER_RANGE: ${descriptor.id}.${field} has no maximum and no default to fall back on`
          );
        }
        parameters[field] = definition.default;
        continue;
      }
      parameters[field] =
        definition.type === "integer"
          ? random.nextInt(range.minimum, range.maximum)
          : round4(range.minimum + random.nextFloat() * (range.maximum - range.minimum));
    }
    return parameters;
  }

  private numericRange(
    field: string,
    definition: { readonly minimum?: number; readonly maximum?: number },
    override: ParameterRange | undefined
  ): ParameterRange | undefined {
    if (override !== undefined) {
      if (override.maximum < override.minimum) {
        throw new Error(`GENERATOR_PARAMETER_RANGE: ${field} override maximum is below its minimum`);
      }
      return override;
    }
    if (definition.minimum !== undefined && definition.maximum !== undefined) {
      return { minimum: definition.minimum, maximum: definition.maximum };
    }
    return undefined;
  }

  // A generic policy configuration: one weight per component plus a threshold.
  // The weighted-score policy consumes both; majority-vote ignores them. This
  // keeps the generator free of any per-policy branching.
  private policyConfiguration(size: number, random: SeededRandom): Record<string, unknown> {
    const weights = Array.from({ length: size }, () => round4(0.1 + random.nextFloat() * 0.9));
    const threshold = round4(0.1 + random.nextFloat() * 0.5);
    return { weights, threshold };
  }

  private assertSearchSpace(space: SearchSpace): void {
    if (space.strategies.length === 0) {
      throw new Error("GENERATOR_SEARCH_SPACE: at least one strategy is required");
    }
    if (space.compositeSizes.length === 0) {
      throw new Error("GENERATOR_SEARCH_SPACE: at least one composite size is required");
    }
    for (const size of space.compositeSizes) {
      if (!Number.isInteger(size) || size < 1) {
        throw new Error("GENERATOR_SEARCH_SPACE: every composite size must be a positive integer");
      }
      if (size > space.strategies.length) {
        throw new Error(
          `GENERATOR_SEARCH_SPACE: composite size ${size} exceeds the ${space.strategies.length} available strategies`
        );
      }
      if (size > 1 && space.policies.length === 0) {
        throw new Error("GENERATOR_SEARCH_SPACE: composite sizes above one require at least one policy");
      }
    }
  }

  // A parameter range may only narrow within the strategy's own schema bounds,
  // never widen past them: a value outside the schema would fail the strategy's
  // validation and break criterion 1. Validated up front so the failure is a
  // clear configuration error, not a crash midway through a sequence.
  private assertParameterRanges(space: SearchSpace): void {
    const ranges = space.parameterRanges;
    if (ranges === undefined) {
      return;
    }
    for (const [strategyId, fields] of Object.entries(ranges)) {
      const ref = space.strategies.find((strategy) => strategy.id === strategyId);
      if (ref === undefined) {
        throw new Error(`GENERATOR_PARAMETER_RANGE: ${strategyId} is not a strategy in the search space`);
      }
      const properties = this.strategies.resolve(ref).descriptor.parameterSchema.properties;
      for (const [field, range] of Object.entries(fields)) {
        const definition = properties[field];
        if (definition === undefined) {
          throw new Error(`GENERATOR_PARAMETER_RANGE: ${strategyId}.${field} is not a parameter of that strategy`);
        }
        if (definition.type !== "number" && definition.type !== "integer") {
          throw new Error(`GENERATOR_PARAMETER_RANGE: ${strategyId}.${field} is not numeric and cannot take a range`);
        }
        if (range.maximum < range.minimum) {
          throw new Error(`GENERATOR_PARAMETER_RANGE: ${strategyId}.${field} maximum is below its minimum`);
        }
        if (definition.type === "integer" && (!Number.isInteger(range.minimum) || !Number.isInteger(range.maximum))) {
          throw new Error(`GENERATOR_PARAMETER_RANGE: ${strategyId}.${field} must use integer bounds`);
        }
        if (definition.minimum !== undefined && range.minimum < definition.minimum) {
          throw new Error(
            `GENERATOR_PARAMETER_RANGE: ${strategyId}.${field} minimum ${range.minimum} is below the strategy minimum ${definition.minimum}`
          );
        }
        if (definition.maximum !== undefined && range.maximum > definition.maximum) {
          throw new Error(
            `GENERATOR_PARAMETER_RANGE: ${strategyId}.${field} maximum ${range.maximum} is above the strategy maximum ${definition.maximum}`
          );
        }
      }
    }
  }

  private readMaxConsecutiveDuplicates(configuration: Record<string, unknown>): number {
    const raw = configuration.maxConsecutiveDuplicates;
    if (raw === undefined) {
      return DEFAULT_MAX_CONSECUTIVE_DUPLICATES;
    }
    if (typeof raw !== "number" || !Number.isInteger(raw) || raw < 1) {
      throw new Error("GENERATOR_CONFIGURATION: maxConsecutiveDuplicates must be a positive integer");
    }
    return raw;
  }
}
